name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  adaptive_theme: 3.6.0
  equatable: 2.0.5
  get: 4.6.6
  flutter_secure_storage: 9.2.2
  dio: 5.6.0
  hugeicons: ^0.0.7
  html: ^0.15.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
  fonts:
    - family: ClashDisplay
      fonts:
        - asset: fonts/ClashDisplay-Regular.otf
        - asset: fonts/ClashDisplay-Bold.otf
          weight: 700
        - asset: fonts/ClashDisplay-Semibold.otf
          weight: 500
